name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run Pytest with coverage
      run: coverage run -m pytest -s -v
    - name: Print Coverage
      run: coverage report -m
